version: '3.8'
services:
  minecraft-server:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./mods:/mods
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      MEMORY: "2G"
      MODS: "/mods"
      TYPE: "FORGE"
      FORGEVERSION: "latest"
